### ISSUE TITLE
Problems because of calls to unexisting numpy method

### ISSUE THREAD

**Issue by cruizdeg** [hemanthpruthvi/PyAstroPol#3]
numpy.int throws errors

**Comment by hemanthpruthvi** [comment]
Hi, sorry for the late response. It's because numpy.int was deprecated in v1.20 whereas the code was developed using v1.18. I assume you were using "Source", because I could find only one instance in "Source.py" where this function was used.

I updated the code and please download the latest "Source.py" to replace the old one. Let me know if there is any issue.

**Comment by cruizdeg** [comment]
No worries, thanks a lot for the reply in anycase I made locally the corrections and was able to run the example code: 
![imagen](https://github.com/user-attachments/assets/3a25efdb-4b39-488a-9979-79301a6a3bd3)
It's been a very fast reply, I thought from the history that the project was more or less "abandoned". I'll come back to you if I have further issues :-)

**Comment by hemanthpruthvi** [comment]
I am glad it worked out. The project is not on the burner as it's sufficient for my present needs. But if you need further support, I will be happy to help.
